In [33]:
import pandas as pd
import numpy as np

from tqdm import tqdm

from sklearn.ensemble import RandomForestClassifier

In [34]:
data = pd.read_csv(r"../ubiquitination/Oryza_sativa/feature_combine/Oryza_train_feature_combine.csv")
data

,label,CKSAAP_1,CKSAAP_2,CKSAAP_3,CKSAAP_4,CKSAAP_5,CKSAAP_6,CKSAAP_7,CKSAAP_8,CKSAAP_9,...,PSSM_611,PSSM_612,PSSM_613,PSSM_614,PSSM_615,PSSM_616,PSSM_617,PSSM_618,PSSM_619,PSSM_620
0,1.0,0.173913,0.136364,0.142857,0.100000,0.0,0.0,0.0,0.0,0.0,...,0.03515,-0.31633,0.03515,1.44106,-0.66781,-0.31633,-0.31633,1.08958,3.19845,-0.31633
1,1.0,0.033333,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,-0.92242,0.34988,-0.28627,-0.92242,-0.28627,2.89448,0.98603,-1.55857,-0.92242,-0.92242
2,1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,-0.62025,0.26582,-0.17721,-1.06329,3.81011,0.26582,0.26582,-1.06329,-0.62025,-0.17721
3,1.0,0.066667,0.034483,0.071429,0.074074,0.0,0.0,0.0,0.0,0.0,...,-0.83745,0.48484,-0.83745,-0.83745,0.04408,0.48484,0.04408,-0.83745,-0.83745,-0.83745
4,1.0,0.000000,0.000000,0.000000,0.037037,0.0,0.0,0.0,0.0,0.0,...,1.28554,-0.40041,3.39299,0.44256,-0.82190,-0.40041,0.02107,-0.40041,0.02107,0.44256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.26497,-0.39745,-0.06624,-0.39745,-0.39745,0.26497,0.26497,-0.39745,-0.39745,0.26497
6996,0.0,0.033333,0.000000,0.000000,0.037037,0.0,0.0,0.0,0.0,0.0,...,0.26497,-0.39745,-0.06624,-0.39745,-0.39745,0.26497,0.26497,-0.39745,-0.39745,0.26497
6997,0.0,0.033333,0.103448,0.035714,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.26497,-0.39745,-0.06624,-0.39745,-0.39745,0.26497,0.26497,-0.39745,-0.39745,0.26497
6998,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,-0.63808,-0.10635,-0.10635,-1.16981,-0.10635,0.95712,3.61577,-1.16981,-0.63808,0.42538
6999,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.03515,-0.31633,0.03515,1.44106,-0.66781,-0.31633,-0.31633,1.08958,3.19845,-0.31633

In [35]:
feature_df = data.iloc[:,1:]
var = np.var(feature_df,axis=0)
feature_name = var.index.tolist()
res = []
for i in range(len(var)):
    if not var[i]==0:
        res.append(i)
feature_var = [feature_name[i] for i in res]
feature_var.insert(0,'label')
df = data.loc[:,feature_var]
df

,label,CKSAAP_1,CKSAAP_2,CKSAAP_3,CKSAAP_4,CKSAAP_6,CKSAAP_7,CKSAAP_8,CKSAAP_9,CKSAAP_11,...,PSSM_611,PSSM_612,PSSM_613,PSSM_614,PSSM_615,PSSM_616,PSSM_617,PSSM_618,PSSM_619,PSSM_620
0,1.0,0.173913,0.136364,0.142857,0.100000,0.0,0.0,0.0,0.0,0.043478,...,0.03515,-0.31633,0.03515,1.44106,-0.66781,-0.31633,-0.31633,1.08958,3.19845,-0.31633
1,1.0,0.033333,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,-0.92242,0.34988,-0.28627,-0.92242,-0.28627,2.89448,0.98603,-1.55857,-0.92242,-0.92242
2,1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.033333,...,-0.62025,0.26582,-0.17721,-1.06329,3.81011,0.26582,0.26582,-1.06329,-0.62025,-0.17721
3,1.0,0.066667,0.034483,0.071429,0.074074,0.0,0.0,0.0,0.0,0.066667,...,-0.83745,0.48484,-0.83745,-0.83745,0.04408,0.48484,0.04408,-0.83745,-0.83745,-0.83745
4,1.0,0.000000,0.000000,0.000000,0.037037,0.0,0.0,0.0,0.0,0.000000,...,1.28554,-0.40041,3.39299,0.44256,-0.82190,-0.40041,0.02107,-0.40041,0.02107,0.44256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.26497,-0.39745,-0.06624,-0.39745,-0.39745,0.26497,0.26497,-0.39745,-0.39745,0.26497
6996,0.0,0.033333,0.000000,0.000000,0.037037,0.0,0.0,0.0,0.0,0.000000,...,0.26497,-0.39745,-0.06624,-0.39745,-0.39745,0.26497,0.26497,-0.39745,-0.39745,0.26497
6997,0.0,0.033333,0.103448,0.035714,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.26497,-0.39745,-0.06624,-0.39745,-0.39745,0.26497,0.26497,-0.39745,-0.39745,0.26497
6998,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,-0.63808,-0.10635,-0.10635,-1.16981,-0.10635,0.95712,3.61577,-1.16981,-0.63808,0.42538
6999,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.03515,-0.31633,0.03515,1.44106,-0.66781,-0.31633,-0.31633,1.08958,3.19845,-0.31633

In [36]:
def get_feature_importances(data, shuffle, nb_runs):
    feat_name = data.columns[1:].tolist()
    X = data.values[:, 1:]
    
    y = data['label'].values.copy()
    
    rf = RandomForestClassifier(n_estimators=100, n_jobs=4, random_state=123)
    rf.fit(X, y)
    feature_importances = rf.feature_importances_
    
    imp_df = pd.DataFrame({"feature": feat_name, "importance": feature_importances})
    imp_df_sorted = imp_df.sort_values(by='importance', ascending=False).reset_index(drop=True)
    
    if shuffle:
        null_imp_dfs = []
        for i in tqdm(range(nb_runs)):
            y = np.random.permutation(y)
            rf = RandomForestClassifier(n_estimators=100, n_jobs=4, random_state=123)
            rf.fit(X, y)
            feature_importances = rf.feature_importances_
            null_imp_df = pd.DataFrame({"feature": feat_name, "importance": feature_importances})
            null_imp_df_sorted = null_imp_df.sort_values(by='importance', ascending=False).reset_index(drop=True)
            null_imp_dfs.append(null_imp_df_sorted)
        null_imp_df = pd.concat(null_imp_dfs, keys=range(1, nb_runs + 1))
        imp_df_sorted = null_imp_df

    return imp_df_sorted

In [37]:
actual_imp_df = get_feature_importances(data=df, shuffle=False, nb_runs=0)

In [38]:
actual_imp_df

           feature  importance
0           PWM_14    0.011747
1           PWM_16    0.011702
2           PWM_21    0.009161
3           PWM_13    0.007041
4           PWM_24    0.006989
...            ...         ...
19598   AA531_2437    0.000000
19599  CKSAAP_1251    0.000000
19600   AA531_9844    0.000000
19601   AA531_2436    0.000000
19602    AA531_110    0.000000

[19603 rows x 2 columns]

In [39]:
nonzero_actual_imp_df = actual_imp_df[actual_imp_df['importance'] > 0]
nonzero_actual_imp_df

           feature    importance
0           PWM_14  1.174713e-02
1           PWM_16  1.170240e-02
2           PWM_21  9.160839e-03
3           PWM_13  7.040629e-03
4           PWM_24  6.989270e-03
...            ...           ...
17134  AA531_15405  9.344883e-07
17135  AA531_13257  9.275410e-07
17136  AA531_15523  9.259087e-07
17137  CKSAAP_1581  9.141696e-07
17138   AA531_9199  9.054491e-07

[17139 rows x 2 columns]

In [11]:
null_imp_df = get_feature_importances(data=df, shuffle=True, nb_runs=1000)
null_imp_df.to_csv(r"C:\Users\Li Xiaokang\Desktop\null_importances_result\score_df\train31_RF_sorted_score_df.csv", index=False)

100%|████████████████████████████████████████████████████████████████████████████| 1000/1000 [6:26:24<00:00, 23.18s/it]

In [40]:
null_imp_df = pd.read_csv(r"C:\Users\Li Xiaokang\Desktop\null_importances_result\score_df\Oryza_null_imp_df.csv")

In [41]:
# 根据 'feature' 列分组并计算平均值
null_imp_mean = null_imp_df.groupby('feature')['importance'].mean().reset_index()

feature_scores = []
for f_ in tqdm(nonzero_actual_imp_df['feature']):
    f_actual_imps_gain = nonzero_actual_imp_df.loc[nonzero_actual_imp_df['feature'] == f_, 'importance'].values
    
    # 从 null_imp_mean 中获取对应特征的平均值
    f_null_imp_mean = null_imp_mean.loc[null_imp_mean['feature'] == f_, 'importance'].values[0]

    final_scores = f_actual_imps_gain[0] / f_null_imp_mean
    feature_scores.append((f_, final_scores))

scores_df = pd.DataFrame(feature_scores, columns=['feature', 'final_score'])
sorted_df = scores_df.sort_values(by="final_score", ascending=False).reset_index(drop=True)

100%|███████████████████████████████████████████████████████████████████████████| 17139/17139 [01:14<00:00, 229.49it/s]

In [42]:
sorted_df.to_csv(r"C:\Users\Li Xiaokang\Desktop\null_importances_result\score_df\Oryza_sorted_score_df.csv", index=False)

In [43]:
sorted_df

           feature  final_score
0           PWM_16   103.155870
1           PWM_14    99.760409
2           PWM_21    77.449802
3           PWM_13    60.359420
4           PWM_24    59.658830
...            ...          ...
17134   AA531_9199     0.018352
17135  AA531_15523     0.017324
17136  AA531_12319     0.017250
17137  AA531_13257     0.017245
17138  AA531_15405     0.013534

[17139 rows x 2 columns]

In [44]:
filtered_df = sorted_df.iloc[:round(sorted_df.shape[0]*0.05), :]

In [45]:
filtered_df

         feature  final_score
0         PWM_16   103.155870
1         PWM_14    99.760409
2         PWM_21    77.449802
3         PWM_13    60.359420
4         PWM_24    59.658830
..           ...          ...
852   AA531_2483     2.417478
853  AA531_10687     2.415565
854   AA531_2171     2.415393
855     PSSM_479     2.415375
856   AA531_6307     2.415136

[857 rows x 2 columns]

In [46]:
features_score_sorted = filtered_df['feature'].tolist()

In [47]:
features_score_sorted.insert(0,'label')

In [48]:
train_feat = data[features_score_sorted]

In [49]:
train_feat

,label,PWM_16,PWM_14,PWM_21,PWM_13,PWM_24,PWM_20,PWM_25,PWM_19,PWM_12,...,CKSAAP_431,AA531_11940,CKSAAP_297,AA531_1120,AA531_2660,AA531_2483,AA531_10687,AA531_2171,PSSM_479,AA531_6307
0,1.0,0.040333,0.105000,0.107000,0.062667,0.024667,0.054667,0.061667,0.022000,0.127333,...,0.0,0.0985,0.045455,0.9915,1.0,5.0135,2.4,-0.0855,-0.51112,5.15
1,1.0,0.022333,0.104000,0.080333,0.108000,0.071667,0.064000,0.045333,0.047000,0.127333,...,0.0,0.1300,0.000000,0.5900,0.0,4.7400,-2.0,0.9900,-0.13648,7.05
2,1.0,0.074667,0.037333,0.099667,0.064333,0.072000,0.022333,0.014333,0.032667,0.026000,...,0.0,-0.1600,0.034483,1.1400,0.0,4.6200,1.3,0.0000,-0.50671,4.81
3,1.0,0.089333,0.104000,0.061333,0.064333,0.071667,0.070333,0.106333,0.047000,0.048667,...,0.0,0.1300,0.000000,1.1400,0.0,5.9700,0.0,-0.8900,0.04880,7.05
4,1.0,0.039333,0.104000,0.080333,0.062667,0.034000,0.064000,0.014000,0.099000,0.048667,...,0.0,-0.2500,0.000000,0.4700,1.0,4.4700,0.0,-0.7500,1.15784,7.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,0.0,0.052000,0.045500,0.074000,0.096750,0.039250,0.014500,0.081500,0.051250,0.046750,...,0.0,-0.0800,0.000000,1.1400,1.0,5.9700,0.0,0.9900,1.61157,7.41
6996,0.0,0.085750,0.029000,0.051500,0.066500,0.087750,0.076500,0.084000,0.058250,0.065750,...,0.0,0.6900,0.000000,1.1400,0.0,4.7400,1.3,0.6700,1.61157,3.42
6997,0.0,0.095750,0.083000,0.083750,0.021000,0.090750,0.073000,0.084000,0.050250,0.089250,...,0.0,0.1500,0.000000,1.5600,0.0,2.8700,0.0,0.0000,1.61157,5.15
6998,0.0,0.022000,0.079750,0.040500,0.046000,0.053500,0.076500,0.038000,0.037250,0.065250,...,0.0,0.0600,0.000000,0.5900,0.0,5.9700,4.8,0.9400,0.58684,8.11
6999,0.0,0.048750,0.052750,0.083750,0.063250,0.056500,0.038000,0.021500,0.050250,0.042750,...,0.0,0.0600,0.000000,1.4600,0.0,6.8900,2.7,0.6700,-0.51112,5.65

In [50]:
train_feat.to_csv("C:/Users/Li Xiaokang/Desktop/null_importances_result/Oryza_train_filtered_null_importances_0.05.csv", index=False)